### ISSUE TITLE
Create Github project

### ISSUE THREAD

**Issue by Razpudding** [cmda-the-lab/study-guide#1]

**Comment by wooorm** [comment]
@Razpudding Looks like you’re doing fine!

**Comment by wooorm** [comment]
@Razpudding How can I help?

**Comment by Razpudding** [comment]
Ah sorry if that wasn't clear. I wanted an expert to review the project creation. To see if everything is ok but also to test the reviewing proces :)

**Comment by wooorm** [comment]
Sure, let’s start using it, and review in like 2 weeks?
