### ISSUE TITLE
Debrief with client about our vision for the project

### ISSUE THREAD

**Issue by Razpudding** [cmda-the-lab/study-guide#10]
We came up with our vision of the project. What we think it could be. Now we need to get back to Justus and see how he feels about that.

**Comment by wooorm** [comment]
Debrief here: https://github.com/cmda-the-lab/iteration-1/blob/7d84b87e0c51d33bbe7f8214bf934d8ba74426e9/readme.md

Justus liked the idea, so let’s start!

/cc @Razpudding @pitzzz
