### ISSUE TITLE
Refining descriptions and project names

### ISSUE THREAD

**Issue by pitzzz** [cmda-the-lab/study-guide#11]
Iteration 1 isn't an iteration anymore - it's a project, right? I called it Study Guides 2.0 for now. I also added a description - A dashboard for academy courses, visualizing course data and competencies.

I changed the name of the readme file to debrief

* opened this as an issue, though I'm quite sure it's not the right way :/

**Comment by wooorm** [comment]
Done!

**Comment by wooorm** [comment]
P.S. Don’t forget to ping related people on issues, I missed this!
