### ISSUE TITLE
Set up a concept for the data model

### ISSUE THREAD

**Issue by Razpudding** [cmda-the-lab/study-guide#12]
The idea is to use some data that is currently in the studiegids and write a JSON document that holds that data as well as additional info we'd like the studyguide to have as per the debrief.

**Comment by Razpudding** [comment]
I looked at the vakkenvuller as suggested by Titus but noticed various changes between courses. I don't know what the minimum requirement of info is so I decided to work off of the actual studyguide as the info in there is the bare minimum for our MVP. Used [this example](https://studiegids.hva.nl/studiegids?edu=cmd-vt&phase=Leerjaar%203&path=https%3A%2F%2Fmetadata-fdmci.mijnhva.nl%2FLists%2FDraftMetadata%2FDispForm.aspx%3FID%3D5119).

**Comment by Razpudding** [comment]
I've submitted my suggestion for the basic data model [here](https://github.com/cmda-the-lab/Study-Guide-2.0/blob/master/data_model_concept.json). I think it would be good to do the same for at least one ICT course. Pick a complex one.
Additionally, we should make an alternative version that includes all the properties we would like items in our new studyguide to have. Like the amount of effort needed per week or examples of previous students' work within the course.

**Comment by Razpudding** [comment]
BTW I've checked the JSON against the RFC 4627 standard. It's valid as long as we remove the comments at the top. Didn't know where else to put them and I think they should stay there until we find a better place like a technical design of the whole project.
I think we should use the studiegidsnummer as our primary key in the database. Possible in combination with the starting studyyear in case the number doesn't change every year on its own.

**Comment by Razpudding** [comment]
[This might be a good ICT course ](https://studiegids.hva.nl/studiegids?edu=hbo-ict-ti-vt&acy=2018-2019&phase=4.%20Specifiek%20themasemester&path=https%3A%2F%2Fmetadata-fdmci.mijnhva.nl%2FLists%2FDraftMetadata%2FDispForm.aspx%3FID%3D5723)to add to the json file.

**Comment by wooorm** [comment]
@Razpudding Anything specifically you’d like me to look at?
Also: we should ask Justus about the data model, and how he’d like this project to be scoped. Maybe ICT and “entry requirements” are of interest, maybe not?

**Comment by Razpudding** [comment]
Just wanted to know if you agree with all the above. Additionally, it would be great if you reworked one other course like the one I suggested to the same JSON format. Justus mentioned that he does want the option to have ICT courses included. Even if he doesn't need it now, it's a good idea to leave room for it in our design. I think we need to allow arbitrary fields in the datamodel as different entries seem to vary in the pieces of info they hold.

**Comment by wooorm** [comment]
Rework: https://github.com/cmda-the-lab/study-guide/blob/master/data-model/index.ts
Let’s discuss tomorrow!

**Comment by wooorm** [comment]
Done, see `data-model`. Feel free to create issues where needed.
