### ISSUE TITLE
Add relevant Asana tasks here

### ISSUE THREAD

**Issue by Razpudding** [cmda-the-lab/study-guide#2]
Please add tasks from Asana that you feel are better situated here

**Comment by wooorm** [comment]
@pitzzz Also for you!

**Comment by pitzzz** [comment]
Not sure if I'm doing it right... Here are the current tasks

* Decide on a project to work on
* Define project scope (sprint plan meeting where we agree on the project deliverable and first sprint deliverable)
* Agree on first sprint ceremonies and any online tools we might need (standups, review and retro) 
* Find students to join

**Comment by pitzzz** [comment]
Is this how todo lists are added here? Is there a higher level for the project tasks?

I've added only the tasks for the next 1/2 meetings

Also, do I need to tag both of you? Or will you get a notification anyways? @Razpudding @wooorm

**Comment by wooorm** [comment]
> Not sure if I'm doing it right... Here are the current tasks

So on GH, you have project boards, you can see one by going to this deep dive repository, and then clicking projects. I just created one for the **meta** repo too.

On these boards, you can have cards. Cards can be quick notes, or an issue (like this one). Issues can have conversations and stuff.

So I think, for a workflow, I would make the four items above into separate notes / issues, based on whether they are quick / require conversation!

> Also, do I need to tag both of you? Or will you get a notification anyways? @Razpudding @wooorm

This depends on if you’re watching a repository or thread. If you want all repositories, you get notified of everything that’s going on. You can do that, but that could theoretically be a lot of notifications!

Typically, once you comment on something, click subscribe to the right, or are pinged, you’ll get notifications for anything going on after that. So, the ping is only needed if someone isn’t subscribed yet!
