### ISSUE TITLE
Defining user stories based on the needs found

### ISSUE THREAD

**Issue by pitzzz** [cmda-the-lab/study-guide#20]
[As ___ I'd like to ____ so I could ____]

[Click here for user stories sheet](https://docs.google.com/spreadsheets/d/1Klp1UnDVOPSPb10sB50Uik1Uu2hPqR4QWJ9WqC4NIDI/edit?usp=drive_web&ouid=113306915574071057808)

**Comment by wooorm** [comment]
No longer needed.
