### ISSUE TITLE
create api (09-28)

### ISSUE THREAD

**Issue by wooorm** [cmda-the-lab/study-guide#25]

**Comment by Razpudding** [comment]
API is capable of returning all routes except competency related stuff as I didn't get to that yet. The logic so far is pretty generic and functions as a placeholder. I've outlined some follow up steps for myself to take. Would like to pursue this myself.[ See work here](https://github.com/cmda-the-lab/study-guide-api).

**Comment by wooorm** [comment]
Looks good!

* For the console.log’s I’d suggest `debug`, of course
* For the `getRecord` function, I believe you could use [`util.promisify`](http://2ality.com/2017/05/util-promisify.html)!

**Comment by wooorm** [comment]
🖕

**Comment by Razpudding** [comment]
Good suggestions! Will likely implement both

**Comment by wooorm** [comment]
Good good! 👍
