### ISSUE TITLE
Some thoughts about competencies

### ISSUE THREAD

**Issue by Razpudding** [cmda-the-lab/study-guide#28]
1. I think competencies can be derived from indicators. That way you only have to fill in indicators as a teacher and the corresponding competency will be computed. Competencies themselves are nothing more than titles so they don't add any information, it's the indicators that have real value.
If we go this way it would suffice to have just a table of indicators and to have courses link to indicators.
2. The way Titus suggested to create the overview is to request a year and then you get back a list of competencies in that year. I think it would make more sense to ask for all courses in a year and derive competencies from that (and then create the overview)

@wooorm What do you think? My suggestion is to have an indicator route and a route to get courses from a certain year. That would be instead of the current year/competency setup

**Comment by wooorm** [comment]
I think we’ve figured this out so I’m closing this.
