### ISSUE TITLE
Create HTML dashboard

### ISSUE THREAD

**Issue by Razpudding** [cmda-the-lab/study-guide#29]

**Comment by Razpudding** [comment]
Convert the draft dashboard design to an html template. The expectation is that the dashboard will work very differently in the end so I'll try to put minimal effort into this task. If you want anything specific from this can you let me know @pitzzz ?

**Comment by Razpudding** [comment]
Talked with @pitzzz and agreed there's no point in making the HTML now. There will first be process to figure out how the HTML has to look and what functionality different views will have and then we just generate the html from the database and add functionality. I'll move this to the backlog so we can work on it later. [MAde this repo alrea](https://github.com/cmda-the-lab/competency-dashboard)dy to hold work

**Comment by wooorm** [comment]
Tracked elsewhere.
