### ISSUE TITLE
Talk with curriculum commitee

### ISSUE THREAD

**Issue by FlorenceHoogveld** [cmda-the-lab/study-guide#31]
- Ask if there's a minimum of competencies a course needs
- Do all competences need to be reviewed per blok / semester / year
- Show current dashboard idea --> What is missing / could be better / other ideas?

**Comment by wooorm** [comment]
@FlorenceHoogveld Any news on this?

**Comment by FlorenceHoogveld** [comment]
@wooorm Not yet unfortunately, since we posted this I've been home because of my windows...

**Comment by wooorm** [comment]
No longer needed.
