### ISSUE TITLE
Update data models

### ISSUE THREAD

**Issue by Razpudding** [cmda-the-lab/study-guide#35]
Talk with titus about synchronizing data models
Update the data models according to the updated data model def on Github

**Comment by Razpudding** [comment]
Also check if enum works

**Comment by Razpudding** [comment]
Check if nul also validates against string (start)

**Comment by Razpudding** [comment]
API needs to add competency field for courses added through post by indicator's competency id. These can simply be taken out of the indicators competencyID field (with a check to make sure it's unique)

**Comment by Razpudding** [comment]
Discuss later @wooorm competency or competencyId (everywhere in the datamodel)
Also discuss: Do we bilaterally or monolaterally

**Comment by Razpudding** [comment]
- Enums work (checked)
- Null will not validate against String, "Null" will. As there's no way to send Null as valid JSON I'm guessing this has already been solved on @wooorm side. Or was this referencing something else? 🤔 
- I'm about to implement this: Upon inserting 1* course(s) through the API, the relevant competencies will be computed by finding the indicators in the DB and looking at their `competency` field. Unique competencies will be added to the relevant course's `competencies` array. If you read this in the next hour or so please give me a call if this implementation doesn't match your input as I don't have any example input on the count of clearing the DB... @wooorm

**Comment by Razpudding** [comment]
As competencies each have several indicators, a competency might be linked to both indicator ...4a and ....4c. This means that as both those indicators reference the same competency, building a list of competencies from indicators would result in many duplicate competencies. 

So the originally proposed method to get a unique list of competencies was this:
For each indicator in a course's `indicators` field, get their id name. This should be something like 0000000004a. If the number part of the Id is already in an array of competency Ids, ignore it, otherwise look up that Indicator and find the relevant competency Id.

I think that logic is a bit dangerous and not future proof so instead I implemented the following method. It's a bit slower but much more future proof:
Look up each indicator in a courses `indicators` field. Get that indicator's `competency` field and store it in an array of competency ids. Then remove duplicates. This is slower because you're doing a lookup before removing duplicates but it will work even if indicator id names change in the future (which they inevitably will).

@wooorm  Please review the code. I have a feeling there is room for optimization as all lookups are handled synchronously. I have a feeling it could be done faster by firing off a bunch of promises that hold each lookup and awaiting Promises.all to make sure the entire array is build before injecting it back into the course but I didn't know quite how to write that code :P

I used the new Set datatype to ensure the uniqueness of values in the array :)

**Comment by Razpudding** [comment]
Relevant code can be found [here](https://github.com/cmda-the-lab/study-guide-api/blob/master/index.js#L118)

**Comment by wooorm** [comment]
@Razpudding You could allow the given competencies, if sent, or otherwise do a lookup to find competency ids from indicator ids, as now. That way it’s slow if you don’t manually compute it, and fast if you like it too.

Other than that, your work is super solid!

**Comment by Razpudding** [comment]
Thanks. I was thinking about a use case for that scenario and then I found it. If a teacher enters a course in the teacher input form they'll select indicators and then we can show them right away which competencies fit to those indicators. So in that case it makes sense to do a post where both the indicators and competencies are already filled in.
I think I'll end up making a separate 'single course POST route' for that which would expect indicators to be filled in. If not I'll implement it in the current 'multiple courses POST route' as suggested.
