### ISSUE TITLE
Find students to join

### ISSUE THREAD

**Issue by wooorm** [cmda-the-lab/study-guide#8]

**Comment by wooorm** [comment]
How’s it going?

**Comment by Razpudding** [comment]
MAde some progress. Reached out to an ICT teacher and student.
The teacher is helping us become a legit entity recognized by the ICT dpt.
The student had the contact of four other students who might be good for the job (all Software Engineering). Asked Roey to follow up with the students.

**Comment by wooorm** [comment]
No longer needed.
