### ISSUE TITLE
Follow up with graduates

### ISSUE THREAD

**Issue by wooorm** [cmda-the-lab/study-guide#9]
Let them know what project we will work on and what they can expect. I think we have a better chance that way.

**Comment by Razpudding** [comment]
Sent a follow up message to Sonja to be sent to graduates. Will close this when she confirms she's sent it.

**Comment by wooorm** [comment]
Any response?

**Comment by Razpudding** [comment]
Sonja is quite busy, but she told me she'd do it.. I'll just close this I guess
